//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts_Table
    {
        public int ShiftsID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Start_Time { get; set; }
        public Nullable<int> End_Time { get; set; }
    }
}
