//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Table
    {
        public int UsersID { get; set; }
        public string Full_Name { get; set; }
        public string User_Name { get; set; }
        public int Num_Of_Actions { get; set; }
    }
}
